# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Meli
email: me@michaelmeli.com
description: > # this means to ignore newlines until "baseurl:"
  Meet Michael Meli
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://michaelmeli.com" # the base hostname & protocol for your site
github_username:  mjmeli
include: ['projects']

# Build settings
markdown: kramdown
